# These are supported funding model platforms
# This is a fork of coreyhaines31/marketingskills
# Keeping original funding links to credit the original creator

github: coreyhaines31
buy_me_a_coffee: coreyhaines
